CREATE TABLE "public"."tenant_ permissions" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "service_user" bigint                   NOT NULL,
  "tenant"       text                     NOT NULL,
  CONSTRAINT "tenant_ permissions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."tenant_ permissions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."service_users" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "full_name"     text,
  "supabase_user" uuid                     NOT NULL,
  CONSTRAINT "service_users_pkey" PRIMARY KEY (id),
  CONSTRAINT "service_users_supabase_user_key" UNIQUE (supabase_user)
);

ALTER TABLE "public"."service_users"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."tenants" (
  "id"         text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text                     NOT NULL,
  "domain"     text                     NOT NULL,
  CONSTRAINT "tenants_domain_key" UNIQUE (DOMAIN),
  CONSTRAINT "tenants_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."tenants"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tenant_ permissions"
  ADD CONSTRAINT "tenant_ permissions_service_user_fkey" FOREIGN KEY (service_user) REFERENCES public.service_users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."service_users"
  ADD CONSTRAINT "service_users_supabase_user_fkey" FOREIGN KEY (supabase_user) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."tenant_ permissions"
  ADD CONSTRAINT "tenant_ permissions_tenant_fkey" FOREIGN KEY (tenant) REFERENCES public.tenants(id) ON UPDATE CASCADE ON DELETE CASCADE;

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tenant_ permissions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."service_users" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tenants" TO "anon", "authenticated", "postgres", "service_role";
